### ISSUE TITLE
How to customize each of cell height?

### ISSUE THREAD

**Issue by hemangshah** [KieranLafferty/KLScrollSelect#4]
I can able to pass height for each of column, and its working fine, that its setting up height for each of the cell in column. What if I want to set custom height for individual cell? How can I do that? Any datasource I'm missing?

**Comment by Marcin-Gorny** [comment]
@hemangshah My pull request (#10) allows each column to have different height.

Cheers,
MG

**Comment by hemangshah** [comment]
Thanks @Marcin (y) :)
